# Generated by Django 4.1.3 on 2022-11-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_id_alter_comment_id_alter_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='active',
            field=models.BooleanField(default='False'),
        ),
    ]
