# Generated by Django 4.1.3 on 2022-11-26 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bid_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='', unique=True)),
                ('startbid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='Item/')),
                ('active', models.BooleanField(default='False')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Itemistuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.AlterField(
            model_name='bid',
            name='lists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.list'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.list'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
